### PR TITLE
Big PEP8 Overhaul, removed mixed tab/space indeting

### PR DESCRIPTION
**Pull request by JuanPotato**

### CODE REVIEW

**Comment by JuanPotato** [comment]
oh, I couldn't test everything, so just tell me when you get an error

**Comment by ender-null** [comment]
Yeah, I added the imports that you commented to the plugins that used them,
like 'about', 'admin', etc.
Thank you man.

2015-11-16 19:39 GMT+01:00 Juan Potato notifications@github.com:

**Comment by JuanPotato** [comment]
wait, before, did the imports actually work? like the plugins were imported and then got the functions and imports of that file?

**Comment by ender-null** [comment]
that imports were used by some plugins, but maybe its better to have them
on the specific plugins that use them.

2015-11-16 20:12 GMT+01:00 Juan Potato notifications@github.com:

**Comment by JuanPotato** [comment]
it worked though?

> but maybe its better to have them on the specific plugins that use them.

yeah

**Comment by ender-null** [comment]
I still need to fix some stuff.

2015-11-16 20:18 GMT+01:00 Juan Potato notifications@github.com:

**Pull request merged**
